FROM python:3.14
WORKDIR /
COPY ./pyproject.toml ./pyproject.toml
RUN echo 'Asia/Shanghai' > /etc/timezone \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN python -m pip install --upgrade pip \
    && pip install uv \
    && uv sync
