FROM python:3.8
WORKDIR /
COPY ./requirements.in ./requirements.in
RUN echo 'Asia/Shanghai' > /etc/timezone \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN python -m pip install --upgrade pip \
    && pip install pip-tools \
    && pip-compile requirements.in -o requirements.txt \
    && pip install -r requirements.txt \
    && rm -f ./requirements.in \
    && rm -f ./requirements.txt
