# -*- coding: utf-8 -*-
# @FILE    : model_consts.py
# @AUTH    : model_creater


from enum import Enum

USER_AUTH_TTYPE_PHONE = 1
USER_AUTH_TTYPE_EMAIL = 2

USER_AUTH_TTYPE_LIST = [
    (USER_AUTH_TTYPE_PHONE, '手机号'),
    (USER_AUTH_TTYPE_EMAIL, '邮箱'),
]

USER_AUTH_IFVERIFIED_TRUE = 1
USER_AUTH_IFVERIFIED_FALSE = 2

USER_AUTH_IFVERIFIED_LIST = [
    (USER_AUTH_IFVERIFIED_TRUE, '是'),
    (USER_AUTH_IFVERIFIED_FALSE, '否'),
]
