# -*- coding: utf-8 -*-
# @File    : CacheChart.py
# @AUTH    : model_creater

CACHE_CHART_TTYPE_SHOW = 1
CACHE_CHART_TTYPE_DOWNLOAD = 2
CACHE_CHART_TTYPE_DATAFILTER = 3

CACHE_CHART_TTYPE_LIST = [
    (CACHE_CHART_TTYPE_SHOW, '图表展示'),
    (CACHE_CHART_TTYPE_DOWNLOAD, '图表下载'),
    (CACHE_CHART_TTYPE_DATAFILTER, '筛选器展示'),
]

CACHE_CHART_STATUS_UNDONE = 1
CACHE_CHART_STATUS_SUCCESS = 2
CACHE_CHART_STATUS_FAILED = 3

CACHE_CHART_STATUS_LIST = [
    (CACHE_CHART_STATUS_UNDONE, '未完成'),
    (CACHE_CHART_STATUS_SUCCESS, '成功'),
    (CACHE_CHART_STATUS_FAILED, '失败'),
]
