# -*- coding: utf-8 -*-
# @File    : Column.py
# @AUTH    : model_creater
# @Time    : 2019-04-03 15:07:20

COLUMN_DTYPE_INT = 1
COLUMN_DTYPE_STRING = 2
COLUMN_DTYPE_FLOAT = 3
COLUMN_DTYPE_OBJECT = 4
COLUMN_DTYPE_LONGTEXT = 5
COLUMN_DTYPE_DATETIME = 6
COLUMN_DTYPE_DATETIME_Y = 7
COLUMN_DTYPE_DATETIME_Q = 8
COLUMN_DTYPE_DATETIME_M = 9
COLUMN_DTYPE_DATETIME_W = 10
COLUMN_DTYPE_DATETIME_WD = 11
COLUMN_DTYPE_DATETIME_D = 12

COLUMN_DTYPE_LIST = [
    (COLUMN_DTYPE_INT, 'int'),
    (COLUMN_DTYPE_STRING, 'string'),
    (COLUMN_DTYPE_FLOAT, 'float'),
    (COLUMN_DTYPE_OBJECT, 'object'),
    (COLUMN_DTYPE_LONGTEXT, 'longtext'),
    (COLUMN_DTYPE_DATETIME, 'datetime'),
    (COLUMN_DTYPE_DATETIME_Y, 'datetime_y'),
    (COLUMN_DTYPE_DATETIME_Q, 'datetime_q'),
    (COLUMN_DTYPE_DATETIME_M, 'datetime_m'),
    (COLUMN_DTYPE_DATETIME_W, 'datetime_w'),
    (COLUMN_DTYPE_DATETIME_WD, 'datetime_wd'),
    (COLUMN_DTYPE_DATETIME_D, 'datetime_d'),
]

COLUMN_TTYPE_NORMAL = 1
COLUMN_TTYPE_CALC = 2
COLUMN_TTYPE_GROUP = 3

COLUMN_TTYPE_LIST = [
    (COLUMN_TTYPE_NORMAL, '普通'),
    (COLUMN_TTYPE_CALC, '计算'),
    (COLUMN_TTYPE_GROUP, '分组'),
]
