# -*- coding: utf-8 -*-
# @File    : Datamerge.py
# @AUTH    : model_creater

DATAMERGE_HOW_INNER = 1
DATAMERGE_HOW_LEFT = 2
DATAMERGE_HOW_RIGHT = 3
DATAMERGE_HOW_OUTER = 4
DATAMERGE_HOW_CONCAT = 5

DATAMERGE_HOW_LIST = [
    (DATAMERGE_HOW_INNER, '内联'),
    (DATAMERGE_HOW_LEFT, '左联'),
    (DATAMERGE_HOW_RIGHT, '右联'),
    (DATAMERGE_HOW_OUTER, '外联'),
    (DATAMERGE_HOW_CONCAT, '上下'),
]
