# -*- coding: utf-8 -*-
# @File    : Datafilter.py
# @AUTH    : model_creater

DATAFILTER_DTYPE_INT = 1
DATAFILTER_DTYPE_STRING = 2
DATAFILTER_DTYPE_FLOAT = 3
DATAFILTER_DTYPE_OBJECT = 4
DATAFILTER_DTYPE_LONGTEXT = 5
DATAFILTER_DTYPE_DATETIME = 6
DATAFILTER_DTYPE_DATETIME_Y = 7
DATAFILTER_DTYPE_DATETIME_Q = 8
DATAFILTER_DTYPE_DATETIME_M = 9
DATAFILTER_DTYPE_DATETIME_W = 10
DATAFILTER_DTYPE_DATETIME_WD = 11
DATAFILTER_DTYPE_DATETIME_D = 12

DATAFILTER_DTYPE_LIST = [
    (DATAFILTER_DTYPE_INT, 'int'),
    (DATAFILTER_DTYPE_STRING, 'string'),
    (DATAFILTER_DTYPE_FLOAT, 'float'),
    (DATAFILTER_DTYPE_OBJECT, 'object'),
    (DATAFILTER_DTYPE_LONGTEXT, 'longtext'),
    (DATAFILTER_DTYPE_DATETIME, 'datetime'),
    (DATAFILTER_DTYPE_DATETIME_Y, 'datetime_y'),
    (DATAFILTER_DTYPE_DATETIME_Q, 'datetime_q'),
    (DATAFILTER_DTYPE_DATETIME_M, 'datetime_m'),
    (DATAFILTER_DTYPE_DATETIME_W, 'datetime_w'),
    (DATAFILTER_DTYPE_DATETIME_WD, 'datetime_wd'),
    (DATAFILTER_DTYPE_DATETIME_D, 'datetime_d'),
]
