# -*- coding: utf-8 -*-
# @File    : Field.py
# @AUTH    : model_creater
# @Time    : 2019-04-03 15:07:20

FIELD_AGG_TYPE_COUNT = 1
FIELD_AGG_TYPE_NUNIQ = 2
FIELD_AGG_TYPE_SUM = 3
FIELD_AGG_TYPE_MEAN = 4
FIELD_AGG_TYPE_MEDIAN = 5
FIELD_AGG_TYPE_MAX = 6
FIELD_AGG_TYPE_MIN = 7

FIELD_AGG_TYPE_LIST = [
    (FIELD_AGG_TYPE_COUNT, '计数'),
    (FIELD_AGG_TYPE_NUNIQ, '去重计数'),
    (FIELD_AGG_TYPE_SUM, '求和'),
    (FIELD_AGG_TYPE_MEAN, '平均值'),
    (FIELD_AGG_TYPE_MEDIAN, '中位数'),
    (FIELD_AGG_TYPE_MAX, '最大值'),
    (FIELD_AGG_TYPE_MIN, '最小值'),
]

FIELD_MULTI_AGG_TYPE_NONE = 1
FIELD_MULTI_AGG_TYPE_CHAIN_RATIO = 2
FIELD_MULTI_AGG_TYPE_CHAIN_CHANGE = 3

FIELD_MULTI_AGG_TYPE_LIST = [
    (FIELD_MULTI_AGG_TYPE_NONE, '正常'),
    (FIELD_MULTI_AGG_TYPE_CHAIN_RATIO, '环比'),
    (FIELD_MULTI_AGG_TYPE_CHAIN_CHANGE, '对比'),
]

FIELD_DATE_TYPE_YEAR = 1
FIELD_DATE_TYPE_QUARTER = 2
FIELD_DATE_TYPE_MONTH = 3
FIELD_DATE_TYPE_WEEK = 4
FIELD_DATE_TYPE_WEEKDAY = 5
FIELD_DATE_TYPE_DAY = 6

FIELD_DATE_TYPE_LIST = [
    (FIELD_DATE_TYPE_YEAR, '按年'),
    (FIELD_DATE_TYPE_QUARTER, '按季'),
    (FIELD_DATE_TYPE_MONTH, '按月'),
    (FIELD_DATE_TYPE_WEEK, '按周'),
    (FIELD_DATE_TYPE_WEEKDAY, '按星期'),
    (FIELD_DATE_TYPE_DAY, '按天'),
]

FIELD_TTYPE_BAR = 1
FIELD_TTYPE_BAR_STACK = 2
FIELD_TTYPE_BAR_STACK_PERCENT = 3
FIELD_TTYPE_HBAR = 4
FIELD_TTYPE_HBAR_STACK = 5
FIELD_TTYPE_HBAR_STACK_PERCENT = 6
FIELD_TTYPE_BARLINE = 7
FIELD_TTYPE_BARLINE_STACK = 8
FIELD_TTYPE_BARLINE_LINE = 9
FIELD_TTYPE_LINE = 10
FIELD_TTYPE_LINE_SHADOW = 11
FIELD_TTYPE_LINE_STACK = 12
FIELD_TTYPE_PIE = 13
FIELD_TTYPE_RADAR = 14
FIELD_TTYPE_SCATTER = 15
FIELD_TTYPE_MAP = 16
FIELD_TTYPE_GAUGE = 17
FIELD_TTYPE_INDEX_CARD = 18
FIELD_TTYPE_TABLE = 19
FIELD_TTYPE_RICHTEXT = 20
FIELD_TTYPE_CUSTOM_MADE = 21
FIELD_TTYPE_SUB_BAR = 22
FIELD_TTYPE_SUB_LINE = 23
FIELD_TTYPE_GRID_BAR = 24
FIELD_TTYPE_GRID_HBAR = 25
FIELD_TTYPE_GRID_LINE = 26
FIELD_TTYPE_MARKLINE = 27

FIELD_TTYPE_LIST = [
    (FIELD_TTYPE_BAR, '柱状图'),
    (FIELD_TTYPE_BAR_STACK, '堆积柱状图'),
    (FIELD_TTYPE_BAR_STACK_PERCENT, '百分比堆积柱状图'),
    (FIELD_TTYPE_HBAR, '条形图'),
    (FIELD_TTYPE_HBAR_STACK, '堆积条形图'),
    (FIELD_TTYPE_HBAR_STACK_PERCENT, '百分比堆积条形图'),
    (FIELD_TTYPE_BARLINE, '柱状折线图'),
    (FIELD_TTYPE_BARLINE_STACK, '堆积柱状折线图'),
    (FIELD_TTYPE_BARLINE_LINE, '柱状折线图折线'),
    (FIELD_TTYPE_LINE, '折线图'),
    (FIELD_TTYPE_LINE_SHADOW, '折线阴影图'),
    (FIELD_TTYPE_LINE_STACK, '堆积折线图'),
    (FIELD_TTYPE_PIE, '饼图'),
    (FIELD_TTYPE_RADAR, '雷达图'),
    (FIELD_TTYPE_SCATTER, '散点图'),
    (FIELD_TTYPE_MAP, '地图'),
    (FIELD_TTYPE_GAUGE, '仪表盘'),
    (FIELD_TTYPE_INDEX_CARD, '指标卡'),
    (FIELD_TTYPE_TABLE, '表格'),
    (FIELD_TTYPE_RICHTEXT, '富文本'),
    (FIELD_TTYPE_CUSTOM_MADE, '私人定制'),
    (FIELD_TTYPE_SUB_BAR, '柱状折线图柱状丛轴'),
    (FIELD_TTYPE_SUB_LINE, '柱状折线图折线丛轴'),
    (FIELD_TTYPE_GRID_BAR, '子图柱状图'),
    (FIELD_TTYPE_GRID_HBAR, '子图横图'),
    (FIELD_TTYPE_GRID_LINE, '子图折线图'),
    (FIELD_TTYPE_MARKLINE, '标志线'),
]

FIELD_DTYPE_INT = 1
FIELD_DTYPE_STRING = 2
FIELD_DTYPE_FLOAT = 3
FIELD_DTYPE_OBJECT = 4
FIELD_DTYPE_LONGTEXT = 5
FIELD_DTYPE_DATETIME = 6
FIELD_DTYPE_DATETIME_Y = 7
FIELD_DTYPE_DATETIME_Q = 8
FIELD_DTYPE_DATETIME_M = 9
FIELD_DTYPE_DATETIME_W = 10
FIELD_DTYPE_DATETIME_WD = 11
FIELD_DTYPE_DATETIME_D = 12

FIELD_DTYPE_LIST = [
    (FIELD_DTYPE_INT, 'int'),
    (FIELD_DTYPE_STRING, 'string'),
    (FIELD_DTYPE_FLOAT, 'float'),
    (FIELD_DTYPE_OBJECT, 'object'),
    (FIELD_DTYPE_LONGTEXT, 'longtext'),
    (FIELD_DTYPE_DATETIME, 'datetime'),
    (FIELD_DTYPE_DATETIME_Y, 'datetime_y'),
    (FIELD_DTYPE_DATETIME_Q, 'datetime_q'),
    (FIELD_DTYPE_DATETIME_M, 'datetime_m'),
    (FIELD_DTYPE_DATETIME_W, 'datetime_w'),
    (FIELD_DTYPE_DATETIME_WD, 'datetime_wd'),
    (FIELD_DTYPE_DATETIME_D, 'datetime_d'),
]

FIELD_STYPE_INDEX = 1
FIELD_STYPE_VALUE = 2
FIELD_STYPE_SUB_VALUE = 3
FIELD_STYPE_COLOR_VALUE = 4
FIELD_STYPE_GRID_VALUE = 5
FIELD_STYPE_TAG_VALUE = 6
FIELD_STYPE_VALUE_X = 7
FIELD_STYPE_VALUE_Y = 8
FIELD_STYPE_COLORTAG = 9
FIELD_STYPE_MARKLINE = 10

FIELD_STYPE_LIST = [
    (FIELD_STYPE_INDEX, '维度'),
    (FIELD_STYPE_VALUE, '度量'),
    (FIELD_STYPE_SUB_VALUE, '从轴'),
    (FIELD_STYPE_COLOR_VALUE, '颜色饱和度'),
    (FIELD_STYPE_GRID_VALUE, '从图度量'),
    (FIELD_STYPE_TAG_VALUE, '文本标签'),
    (FIELD_STYPE_VALUE_X, 'X轴度量'),
    (FIELD_STYPE_VALUE_Y, 'Y轴度量'),
    (FIELD_STYPE_COLORTAG, '图例'),
    (FIELD_STYPE_MARKLINE, '辅助线'),
]
