name: docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: login aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image to aliyuncs
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/swxs/home .
          docker push ${{ secrets.DOCKER_REGISTRY }}/swxs/home
